Creating Day1- Ex03
mmul-it/training pull request #4
Opened 2019-11-11 13:36 UTC by mbrigida

* Created Exercise003
* Created Exercise003.solutions

2019-11-18 15:36 UTC, rascasoft requested changes
Few changes and we're good to go.

2019-11-18 15:36 UTC, rascasoft commented on MMUL-BASH-01/Exercises/Day-1/Exercise.003
> +2) print the string "# Exercise 003 - Redirect STDOUT" to a file called
Start with capital letter each section, you're mixing capital and lowercase.

2019-11-18 15:36 UTC, rascasoft commented on MMUL-BASH-01/Exercises/Day-1/Exercise.003
> +"output_data" in your HOMEDIR;
Align the second line with the previous text, like:
```
1) First line starts here
   Second starts here.
```

2019-11-19 08:49 UTC, mbrigida commented
Capitalization at start of each section, text aligned with previous text

2019-11-19 14:45 UTC, rascasoft approved these changes
Looks good to me.

2019-11-19 14:45 UTC, merged